/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as SnaRouteImport } from './routes/sna'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SentimentRouteImport } from './routes/sentiment'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RssRouteImport } from './routes/rss'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PredictionRouteImport } from './routes/prediction'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MediaRouteImport } from './routes/media'
import { Route as MapRouteImport } from './routes/map'
import { Route as ExportRouteImport } from './routes/export'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComparativeRouteImport } from './routes/comparative'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SnaRoute = SnaRouteImport.update({
  id: '/sna',
  path: '/sna',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SentimentRoute = SentimentRouteImport.update({
  id: '/sentiment',
  path: '/sentiment',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RssRoute = RssRouteImport.update({
  id: '/rss',
  path: '/rss',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionRoute = PredictionRouteImport.update({
  id: '/prediction',
  path: '/prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportRoute = ExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparativeRoute = ComparativeRouteImport.update({
  id: '/comparative',
  path: '/comparative',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparative': typeof ComparativeRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/map': typeof MapRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/prediction': typeof PredictionRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/rss': typeof RssRoute
  '/search': typeof SearchRoute
  '/sentiment': typeof SentimentRoute
  '/settings': typeof SettingsRoute
  '/sna': typeof SnaRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparative': typeof ComparativeRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/map': typeof MapRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/prediction': typeof PredictionRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/rss': typeof RssRoute
  '/search': typeof SearchRoute
  '/sentiment': typeof SentimentRoute
  '/settings': typeof SettingsRoute
  '/sna': typeof SnaRoute
  '/trends': typeof TrendsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comparative': typeof ComparativeRoute
  '/dashboard': typeof DashboardRoute
  '/export': typeof ExportRoute
  '/map': typeof MapRoute
  '/media': typeof MediaRoute
  '/news': typeof NewsRoute
  '/prediction': typeof PredictionRoute
  '/profile': typeof ProfileRoute
  '/recommendations': typeof RecommendationsRoute
  '/rss': typeof RssRoute
  '/search': typeof SearchRoute
  '/sentiment': typeof SentimentRoute
  '/settings': typeof SettingsRoute
  '/sna': typeof SnaRoute
  '/trends': typeof TrendsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comparative'
    | '/dashboard'
    | '/export'
    | '/map'
    | '/media'
    | '/news'
    | '/prediction'
    | '/profile'
    | '/recommendations'
    | '/rss'
    | '/search'
    | '/sentiment'
    | '/settings'
    | '/sna'
    | '/trends'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comparative'
    | '/dashboard'
    | '/export'
    | '/map'
    | '/media'
    | '/news'
    | '/prediction'
    | '/profile'
    | '/recommendations'
    | '/rss'
    | '/search'
    | '/sentiment'
    | '/settings'
    | '/sna'
    | '/trends'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/comparative'
    | '/dashboard'
    | '/export'
    | '/map'
    | '/media'
    | '/news'
    | '/prediction'
    | '/profile'
    | '/recommendations'
    | '/rss'
    | '/search'
    | '/sentiment'
    | '/settings'
    | '/sna'
    | '/trends'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComparativeRoute: typeof ComparativeRoute
  DashboardRoute: typeof DashboardRoute
  ExportRoute: typeof ExportRoute
  MapRoute: typeof MapRoute
  MediaRoute: typeof MediaRoute
  NewsRoute: typeof NewsRoute
  PredictionRoute: typeof PredictionRoute
  ProfileRoute: typeof ProfileRoute
  RecommendationsRoute: typeof RecommendationsRoute
  RssRoute: typeof RssRoute
  SearchRoute: typeof SearchRoute
  SentimentRoute: typeof SentimentRoute
  SettingsRoute: typeof SettingsRoute
  SnaRoute: typeof SnaRoute
  TrendsRoute: typeof TrendsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sna': {
      id: '/sna'
      path: '/sna'
      fullPath: '/sna'
      preLoaderRoute: typeof SnaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentiment': {
      id: '/sentiment'
      path: '/sentiment'
      fullPath: '/sentiment'
      preLoaderRoute: typeof SentimentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss': {
      id: '/rss'
      path: '/rss'
      fullPath: '/rss'
      preLoaderRoute: typeof RssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prediction': {
      id: '/prediction'
      path: '/prediction'
      fullPath: '/prediction'
      preLoaderRoute: typeof PredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export': {
      id: '/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof ExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparative': {
      id: '/comparative'
      path: '/comparative'
      fullPath: '/comparative'
      preLoaderRoute: typeof ComparativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComparativeRoute: ComparativeRoute,
  DashboardRoute: DashboardRoute,
  ExportRoute: ExportRoute,
  MapRoute: MapRoute,
  MediaRoute: MediaRoute,
  NewsRoute: NewsRoute,
  PredictionRoute: PredictionRoute,
  ProfileRoute: ProfileRoute,
  RecommendationsRoute: RecommendationsRoute,
  RssRoute: RssRoute,
  SearchRoute: SearchRoute,
  SentimentRoute: SentimentRoute,
  SettingsRoute: SettingsRoute,
  SnaRoute: SnaRoute,
  TrendsRoute: TrendsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
